routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\EventController;




/*Route::get('/welcome', function () {
    return view('welcome1');
})->name('myhome');*/


Route::get('post/{slug}',[HomeController::class,'show'])->name('single-post');
Route::get('/',[HomeController::class,'index']);

Route::get('category-post/{cat_slug}',[HomeController::class,'categoryPost'])->name('category-post');
Route::get('search',[HomeController::class,'search'])->name('search');



Route::get('/test', function () {
    return view('test');
});


Route::get('test1',function(){
	return route('myhome',['sortBy'=>'name']);
});

/*Route::get('forgot-password',function(){
   return view('auth.passwords.reset');
});*/

Route::get('/home', ['middleware' => ['auth','admin'], function () {
    return view('adminarea.index');
}]);


	
/*Route::get('admin_area', ['middleware' => ['auth','admin'], function () {
    return view('adminarea.index');
}]);*/

Route::group( ['prefix' => 'admin',  'middleware' => ['auth','admin'] ], function()
{
    Route:: view('/home',[AdminController::class,'index']);
    Route:: get('/profile',[AdminController::class,'profile']);
    Route::get('/allposts',[PostController::class,'datatable']);
    Route::get('/allcategory',[CategoryController::class,'datatable']);
    Route::resource('category', CategoryController::class);
	Route::resource('post', PostController::class);
	Route::resource('event', EventController::class);
	Route::post('/storeEvent',[EventController::class,'storeEvent']);


	
});

Route::get('forgot_password',function(){
	return view('auth.passwords.reset');
} );

Route::view('admin','admin.index');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Category extends Model
{
    use HasFactory;
    
    protected $fillable = ['parent_id', 'title','cat_slug'];

    public function children()
    {
      return $this->hasMany('App\Models\Category', 'parent_id')->whereNull('parent_id');
    }

    public function childrenRecursive()
		{
		    return $this->children->with('children');
		}
   public function parent()
    {
      return $this->hasOne('App\Models\Category','id', 'parent_id');
    }	

       public function childs()
      {
          return $this->hasMany('App\Models\Category', 'parent_id', 'id');
      } 



    public function createSlug($title, $id = 0)
      {
          // Normalize the title
          $slug = Str::of($title)->slug('-');


          // Get any that could possibly be related.
          // This cuts the queries down by doing it once.
          $allSlugs = $this->getRelatedSlugs($slug, $id);

          // If we haven't used it before then we are all good.
          if (! $allSlugs->contains('slug', $slug)){
              return $slug;
          }

          // Just append numbers like a savage until we find not used.
          for ($i = 1; $i <= 10; $i++) {
              $newSlug = $slug.'-'.$i;
              if (! $allSlugs->contains('slug', $newSlug)) {
                  return $newSlug;
              }
          }

          throw new \Exception('Can not create a unique slug');
      }

      protected function getRelatedSlugs($slug, $id = 0)
      {
          return Post::select('slug')->where('slug', 'like', $slug.'%')
              ->where('id', '<>', $id)
              ->get();
      }



}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Category;
use DataTables;


class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {   
         $query = Category::query();
         $allcategories= $query->with(['children','parent'])->get();
         return view('adminarea.category.index',['allcategories'=>$allcategories]);
   /*    //$categories = Category::with(['children','parent'])->whereNull('parent_id')->get();

        $query = Category::query();

         $order_arr = [];

        if($request->has('search')){
            $search = $request->search;
            $query->where('categories.title', 'like', '%' . $search . '%');

            $order_arr['search'] = $search;
        }

        if($request->has('order_by')){
            if ($request->order_by=='parent_id') {

                $query->join('categories as t2','categories.id','=','t2.id');
                 $order_by = 't2.title';
                 $order_q = $request->order;

            }
            else{
                $order_by = $request->order_by;
                $order_q = $request->order;
            }
            
                       $order = $request->order == 'ASC' ? 'DESC' : 'ASC';
            $order_arr['order_by'] = $order_by;
            $order_arr['order'] = $order;
        }else{
            $order_by = 'id';
            $order_q = 'DESC';
            $order_arr['order_by'] = $order_by;
            $order_arr['order'] = 'ASC';
        }

        if($request->order_by){
           
           
        }

     //    dd($order_by, $order_q);
        $query->orderBy($order_by, $order_q);
        

       // $order = ['order_by' => 'id', 'order' => 'asc'];
        $order = $order_arr;
       // dd($query);


       $allcategories= $query->with(['children','parent'])->paginate(5);*/

       //return view('admin.category.index', compact('order', 'allcategories'));
      
    }

    public function datatable(Request $request){
        $query = Category::select('*');
        return Datatables::of($query)
                ->addColumn('action', function ($category) {
                    return '<button type="button" class="btn btn-sm btn-primary editcategory"  onClick="editCate('.$category->id.',\''.$category->title.'\')" >Edit</button> 

                          <button type="button" class="btn btn-sm btn-danger mr-1 deletecategory"   
                            data-toggle="modal" data-target="#deleteCategoryModal" onClick="deleteCate('.$category->id.')">Delete</button>
                    ';
                })
                ->make(true);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $this->validate($request, [
            'title'      => 'required|min:3|max:255|string',
            'parent_id' => 'sometimes|nullable|numeric',
        ]);

      $query=new Category;
      $query->title = $request->title;
      $query->parent_id = $request->parent_id;
      $query->cat_slug = $query->createSlug($request->title);
      $query->save();


      //Category::create($validatedData);

      return redirect()->back()->withSuccess('You have successfully created a Category!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $otherCategories= Category::where('parent_id','=',null)->get();
        $data=Category::find($id);
        //dd($data);
        $returnHTML = view('adminarea.category.edit')->with(['otherCategories'=>$otherCategories,'parentCategory'=>$data])->render();
        return response()->json(array('success' => true, 'html'=>$returnHTML));
       
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $this->validate($request, [
            'parent_id'     =>  'sometimes|nullable|numeric',
            'title'  => 'required|min:3|max:255|string'
        ]);

        
        Category::where('id',$id)->update($validatedData);

        return redirect()->route('category.index')->withSuccess('You have successfully updated a Category!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         Category::where('id',$id)->delete();

        return redirect()->route('category.index')->withSuccess('You have successfully deleted a Category!');
    }
}

resources/views/admin/category/edit.blade.php
<form id="editPostForm" action="" method="POST">
                    @csrf
                    @method('PUT')

                    
                      <div class="form-group">
                       <select class="form-control" name="parent_id">
                        <option value="">Select Parent Category</option>

                        @foreach ($otherCategories as $category)
                          <option value="{{ $category->id }}" @if ($category->id==$parentCategory->parent_id){{'selected="selected"'}} @endif >{{ $category->title}}</option>
                        @endforeach
                      </select>
                    </div>
                      <div class="form-group">
                        <input type="text" name="title" class="form-control" value="" placeholder="Category Name" required>
                      </div>
              
                   
</form>

resources/views/admin/category/index.blade.php
@extends('layouts.masteradmin')

@section('content')
  <!-- HEADER -->
  <header id="main-header" class="py-2 bg-success text-white">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h1><i class="fas fa-folder"></i> Categories</h1>
        </div>
      </div>
    </div>
  </header>
  <!-- SEARCH -->
  
  <section id="search" class="py-4 mb-4 bg-light">
    <div class="container">
      <div class="row">
        <div class="col-md-4 ml-auto">
          <form action="{{ route('category.index', $order) }}" method="GET">

            <div class="input-group">
            <input type="text" name='search' class="form-control" placeholder="Search Categories..." value="{{request('search')}}">
            <div class="input-group-append">
               
            <div class="form-group">
                      <button type="submit" class="btn btn-success" id="search">Search</button>
            </div>
            </div>
          </form>
          
        </div>
        </div>
      </div>
    </div>
  </section>

  <!-- CATEGORIES -->
  

<!--  -->
@if (Session::has('success'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <h4 class="alert-heading">Success!</h4>
                <p>{{ Session::get('success') }}</p>

                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif

@if (Session::has('errors'))
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">Error!</h4>
        <p>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </p>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

          <div class="container py-3">

            <!-- edit category  model-->

            <div class="modal" tabindex="-1" role="dialog" id="editCategoryModal">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title">Edit Category</h5>

                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>

                  <form action="" method="POST">
                    @csrf
                    @method('PUT')

                    <div class="modal-body" id="categorydata">
                         
                    </div>

                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      <button type="submit" class="btn btn-primary">Update</button>
                    </div>
                  </div>
                  </form>
              </div>
            </div>

            <!-- DELETE MODAL -->

            <div class="modal" tabindex="-1" role="dialog" id="deleteCategoryModal">
                          <div class="modal-dialog" role="document">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title">Delete Category</h5>

                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                                </button>
                              </div>
                            

                              <form action="" method="POST">
                                 @csrf
                                 @method('DELETE')

                                <div class="modal-body">
                                  <div class="form-group">
                                    <p>Are you sure! do you want to delete this category?</p>
                                  </div>
                                </div>

                                <div class="modal-footer">
                                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                  <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                                </div>
                              </div>
                              </form>
                          </div>
            </div>

            <!-- End DELETE MODEL -->

           
          <div class="row">
            <div class="col-md-8">

              <div class="card">
                <div class="card-header">
                  <h3>Categories</h3>
                </div>
                <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">
                          <a href="{{ route('category.index', $order) }}">ID</a>
                          
                        </th>
                        @php
                          $order['order_by'] = 'title';
                        @endphp
                        <th scope="col"><a href="{{ route('category.index', $order) }}">Title</a></th>
                        @php
                          $order['order_by'] = 'parent_id';
                        @endphp
                        <th scope="col"><a href="{{ route('category.index', $order) }}">Parent</a></th>
                        <th scope="col">Action</th>
                      </tr>
                    </thead>
                    @foreach ($allcategories as $category)
                    <tbody>
                      <tr>
                        <th scope="row">{{$category->id}}</th>
                        <td>{{$category->title}}</td>
                         <td>{{!empty($category->parent['title'])?$category->parent['title']:''}}</td>
                        <td>
                          <button type="button" class="btn btn-sm btn-primary editcate"  data-id="{{ $category->id }}" data-title="{{ $category->title }}">Edit</button> 
                          
                          <button type="button" class="btn btn-sm btn-danger mr-1 delete-category" data-toggle="modal" data-target="#deleteCategoryModal" data-id="{{ $category->id }}" data-title="{{ $category->title }}">Delete</button>
                        </td>
                      </tr>
                    </tbody>

                   @endforeach 
                     

                </table>
                  <nav class="ml-4">
                        <ul class="pagination">
                          <li class="page-item ">
                            <a href="{{$allcategories->previousPageUrl()}}" class="page-link">Previous</a>
                          </li>
                          @for($i=1;$i<=$allcategories->lastPage();$i++)
                          <li class="page-item active">
                            <a href="{{$allcategories->url($i)}}" class="page-link active">{{$i}}</a>
                          </li>
                          @endfor
                          
                          <li class="page-item">
                            <a href="{{$allcategories->nextPageUrl()}}" class="page-link">Next</a>
                          </li>
                        </ul>
                      </nav>
              </div>
             

            </div>

          
          
          <!-- create Category -->
            <div class="col-md-4">
              <div class="card">
                <div class="card-header">
                  <h3>Create Category</h3>
                </div>

                <div class="card-body">
                  <form action="{{route('category.store')}}" method="POST">
                    @csrf

                    <div class="form-group">
                      <select class="form-control" name="parent_id">
                        <option value="">Select Parent Category</option>

                        @foreach ($allcategories as $category)
                          <option value="{{ $category->id }}">{{ $category->title }}</option>
                        @endforeach
                      </select>
                    </div>

                    <div class="form-group">
                      <input type="text" name="title" class="form-control" value="{{ old('title') }}" placeholder="Category title" required>
                    </div>

                    <div class="form-group">
                      <button type="submit" class="btn btn-primary">Create</button>
                    </div>
                  </form>
                </div>
              </div>

            </div>
          <!-- End of create Category -->  

          
        </div>

  


 @endsection 

 


@push('js')
        
        <script type="text/javascript">
          

          $('.editcate').on('click', function() {
             var id = $(this).data('id');
             var title = $(this).data('title');
             var myurl = "{{ url('admin/category') }}/" + id + '/edit';
             var updateurl="{{ url('admin/category') }}/" + id ;
             
             $.ajax({
                 type:'GET',
                 url:myurl, //Make sure your URL is correct
                 dataType: 'json', //Make sure your returning data type dffine as json
                 data:'_token = <?php echo csrf_token() ?>',
                 success:function(data){
                  $('#categorydata').html(data.html);
                  console.log(data);  
                 $('#editCategoryModal').modal();
                 $('#editCategoryModal form input[name="title"]').val(title);
                 $('#editCategoryModal form').attr('action', updateurl);
                 
               }
             });


          });


          $('.delete-category').on('click', function() {
            var id = $(this).data('id');
            var url = "{{ url('admin/category') }}/" + id;
            $('#deleteCategoryModal form').attr('action', url);
          });


         /* $('#search').click(function(){
            alert($( "#mysearch option:selected" ).val())
          });*/

        </script>
@endpush        