routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\EventController;




/*Route::get('/welcome', function () {
    return view('welcome1');
})->name('myhome');*/


Route::get('post/{slug}',[HomeController::class,'show'])->name('single-post');
Route::get('/',[HomeController::class,'index']);

Route::get('category-post/{cat_slug}',[HomeController::class,'categoryPost'])->name('category-post');
Route::get('search',[HomeController::class,'search'])->name('search');



Route::get('/test', function () {
    return view('test');
});


Route::get('test1',function(){
	return route('myhome',['sortBy'=>'name']);
});

/*Route::get('forgot-password',function(){
   return view('auth.passwords.reset');
});*/

Route::get('/home', ['middleware' => ['auth','admin'], function () {
    return view('adminarea.index');
}]);


	
/*Route::get('admin_area', ['middleware' => ['auth','admin'], function () {
    return view('adminarea.index');
}]);*/

Route::group( ['prefix' => 'admin',  'middleware' => ['auth','admin'] ], function()
{
    Route:: view('/home',[AdminController::class,'index']);
    Route:: get('/profile',[AdminController::class,'profile']);
    Route::get('/allposts',[PostController::class,'datatable']);
    Route::get('/allcategory',[CategoryController::class,'datatable']);
    Route::resource('category', CategoryController::class);
	Route::resource('post', PostController::class);
	Route::resource('event', EventController::class);
	Route::post('/storeEvent',[EventController::class,'storeEvent']);


	
});

Route::get('forgot_password',function(){
	return view('auth.passwords.reset');
} );

Route::view('admin','admin.index');

resources/views/adminarea/calendar.blade.php
@extends('layouts.adminarea')

@push('css')
 <!-- fullCalendar -->
  <link rel="stylesheet" href="{{asset('plugins/fullcalendar/main.min.css')}}">
  <link rel="stylesheet" href="{{asset('plugins/fullcalendar-daygrid/main.min.css')}}">
  <link rel="stylesheet" href="{{asset('plugins/fullcalendar-timegrid/main.min.css')}}">
  <link rel="stylesheet" href="{{asset('plugins/fullcalendar-bootstrap/main.min.css')}}">
@endpush
  <!-- Content Wrapper. Contains page content -->
@section('content')  
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Calendar</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Calendar</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-3">
            <div class="sticky-top mb-3">
              <div class="card">
                <div class="card-header">
                  <h4 class="card-title">Draggable Events</h4>
                </div>
                <div class="card-body">
                  <!-- the events -->
                  <div id="external-events">
                    @foreach($allEvents as $event)
                      <div class="external-event ui-draggable ui-draggable-handle" style="background-color: {{$event->color}}; border-color:{{$event->color}}; color: rgb(255, 255, 255); position: relative;" id='{{$event->id}}'>{{$event->title}}</div>
                    @endforeach

                   
                    <div class="checkbox">
                      <label for="drop-remove">
                        <input type="checkbox" id="drop-remove">
                        remove after drop
                      </label>
                    </div>
                  </div>
                </div>
                <!-- /.card-body -->
              </div>
              <!-- /.card -->
              <div class="card">
                <div class="card-header">
                  <h3 class="card-title">Create Event</h3>
                </div>
                <div class="card-body">
                  <div class="btn-group" style="width: 100%; margin-bottom: 10px;">
                    <!--<button type="button" id="color-chooser-btn" class="btn btn-info btn-block dropdown-toggle" data-toggle="dropdown">Color <span class="caret"></span></button>-->
                    <ul class="fc-color-picker" id="color-chooser">
                      <li><a class="text-primary" href="#"><i class="fas fa-square"></i></a></li>
                      <li><a class="text-warning" href="#"><i class="fas fa-square"></i></a></li>
                      <li><a class="text-success" href="#"><i class="fas fa-square"></i></a></li>
                      <li><a class="text-danger" href="#"><i class="fas fa-square"></i></a></li>
                      <li><a class="text-muted" href="#"><i class="fas fa-square"></i></a></li>
                    </ul>
                  </div>
                  <!-- /btn-group -->
                  <form method="post" >
                    @csrf
                    <div class="input-group">
                      <input id="new-event" type="text" name='title' class="form-control" placeholder="Event Title">

                      <div class="input-group-append">
                        <button id="add-new-event" type="button" class="btn btn-primary">Add</button>
                      </div>
                      <!-- /btn-group -->
                    </div>
                    <!-- /input-group -->
                  </form>
                </div>
              </div>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-md-9">
            <div class="card card-primary">
              <div class="card-body p-0">
                <!-- THE CALENDAR -->
                <div id="calendar"></div>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
@endsection
  
@push('js')

<!-- jQuery UI -->
<script src="{{asset('plugins/jquery-ui/jquery-ui.min.js')}}"></script>
<!-- AdminLTE App -->

<!-- fullCalendar 2.2.5 -->
<script src="{{asset('plugins/moment/moment.min.js')}}"></script>
<script src="{{asset('plugins/fullcalendar/main.min.js')}}"></script>
<script src="{{asset('plugins/fullcalendar-daygrid/main.min.js')}}"></script>
<script src="{{asset('plugins/fullcalendar-timegrid/main.min.js')}}"></script>
<script src="{{asset('plugins/fullcalendar-interaction/main.min.js')}}"></script>
<script src="{{asset('plugins/fullcalendar-bootstrap/main.min.js')}}"></script>
<!-- Page specific script -->
<script>
  $(function () {

    /* initialize the external events
     -----------------------------------------------------------------*/
    function ini_events(ele) {
      ele.each(function () {

        // create an Event Object (http://arshaw.com/fullcalendar/docs/event_data/Event_Object/)
        // it doesn't need to have a start or end
        var eventObject = {
          title: $.trim($(this).text()) // use the element's text as the event title
        }

        // store the Event Object in the DOM element so we can get to it later
        $(this).data('eventObject', eventObject)

        // make the event draggable using jQuery UI
        $(this).draggable({
          zIndex        : 1070,
          revert        : true, // will cause the event to go back to its
          revertDuration: 0  //  original position after the drag
        })

      })
    }

    ini_events($('#external-events div.external-event'))

    /* initialize the calendar
     -----------------------------------------------------------------*/
    //Date for the calendar events (dummy data)
    var date = new Date()
    var d    = date.getDate(),
        m    = date.getMonth(),
        y    = date.getFullYear()

    var Calendar = FullCalendar.Calendar;
    var Draggable = FullCalendarInteraction.Draggable;

    var containerEl = document.getElementById('external-events');
    var checkbox = document.getElementById('drop-remove');
    var calendarEl = document.getElementById('calendar');

    // initialize the external events
    // -----------------------------------------------------------------

    new Draggable(containerEl, {
      itemSelector: '.external-event',
      eventData: function(eventEl) {
       
        return {
          title: eventEl.innerText,
          backgroundColor: window.getComputedStyle( eventEl ,null).getPropertyValue('background-color'),
          borderColor: window.getComputedStyle( eventEl ,null).getPropertyValue('background-color'),
          textColor: window.getComputedStyle( eventEl ,null).getPropertyValue('color'),
        };
      }
    });

    var calendar = new Calendar(calendarEl, {
      plugins: [ 'bootstrap', 'interaction', 'dayGrid', 'timeGrid' ],
      header    : {
        left  : 'prev,next today',
        center: 'title',
        right : 'dayGridMonth,timeGridWeek,timeGridDay'
      },
       timeZone: 'UTC',
       
      'themeSystem': 'bootstrap',
      //Random default events
      events    : {!! $json !!},
      editable  : true,
      droppable : true, // this allows things to be dropped onto the calendar !!!
      drop      : function(info) {
        // is the "remove after drop" checkbox checked?
        if (checkbox.checked) {
          // if so, remove the element from the "Draggable Events" list
          info.draggedEl.parentNode.removeChild(info.draggedEl);
        }
        
        date=moment(info.dateStr).format('YYYY-MM-DD hh:mm:ss');

        //console.log(date);
        id=$(info.draggedEl).attr('id');
        data={'event_id':id,'date':date}
        $.ajax({
             type:'POST',
             url:'{{url("admin/storeEvent")}}',
             dataType: 'json',
             data:{"_token": "{{ csrf_token() }}","data": data},
             success:function(response){
             console.log(response);
            
           }
          });

        
       // console.log($(info.draggedEl).attr('id'));
      },
      eventDrop: function(info) {
        start=moment(info.event.start.toISOString()).format('YYYY-MM-DD hh:mm:ss');
        console.log(id);
        if (info.event.end==null){
          end=start;
        }else{
           end=moment(info.event.end.toISOString()).format('YYYY-MM-DD hh:mm:ss');
        }
        data={'start':start,'end':end};
        $.ajax({
             type:'POST',
             url:'{{url("admin/updateEvent")/}}'+id,
             dataType: 'json',
             data:{"_token": "{{ csrf_token() }}","data": data},
             success:function(response){
             console.log(response);
            
           }
          });
       
       },

        eventResize: function(info) {
          event_id= id;
          start=info.event.start.toISOString();
          end=info.event.end.toISOString();
          accurance=info.view.type;
          data={'event_id':id,'start':start,'end':end,'accurance': accurance};
          console.log(info.view.type);
          console.log(moment(start).format('YYYY-MM-DD hh:mm:ss'));

          console.log(moment(end).format('YYYY-MM-DD hh:mm:ss'));

          /*start = $.fullCalendar.formatDate(info.event.start.toISOString(), "yyyy-MM-dd");
          console.log(start);*/
        
        
        /*if (!confirm("is this okay?")) {
          info.revert();
        }*/
      }
    });


    calendar.render();
    // $('#calendar').fullCalendar()

    /* ADDING EVENTS */
    var currColor = '#3c8dbc' //Red by default
    //Color chooser button
    var colorChooser = $('#color-chooser-btn')
    $('#color-chooser > li > a').click(function (e) {
      e.preventDefault()
      //Save color
      currColor = $(this).css('color')
      //Add color effect to button
      $('#add-new-event').css({
        'background-color': currColor,
        'border-color'    : currColor
      })
    })
    $('#add-new-event').click(function (e) {
      e.preventDefault()
      //Get value and make sure it is not null
      var val = $('#new-event').val()
      if (val.length == 0) {
        return
      }
      var data={color:currColor,title:val}
      $.ajax({
             type:'POST',
             url:'{{route("event.store")}}',
             dataType: 'json',
             data:{"_token": "{{ csrf_token() }}","data": data},
             success:function(response){
             console.log(response);
            
           }
          });
      //Create events
      var event = $('<div />')
      event.css({
        'background-color': currColor,
        'border-color'    : currColor,
        'color'           : '#fff'
      }).addClass('external-event')
      event.html(val)
      $('#external-events').prepend(event)

      //Add draggable funtionality
      ini_events(event)

      //Remove event from text input
      $('#new-event').val('')
    })
  })//end of main function



</script>
@endpush