routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\EventController;




/*Route::get('/welcome', function () {
    return view('welcome1');
})->name('myhome');*/


Route::get('post/{slug}',[HomeController::class,'show'])->name('single-post');
Route::get('/',[HomeController::class,'index']);

Route::get('category-post/{cat_slug}',[HomeController::class,'categoryPost'])->name('category-post');
Route::get('search',[HomeController::class,'search'])->name('search');



Route::get('/test', function () {
    return view('test');
});


Route::get('test1',function(){
	return route('myhome',['sortBy'=>'name']);
});

/*Route::get('forgot-password',function(){
   return view('auth.passwords.reset');
});*/

Route::get('/home', ['middleware' => ['auth','admin'], function () {
    return view('adminarea.index');
}]);


	
/*Route::get('admin_area', ['middleware' => ['auth','admin'], function () {
    return view('adminarea.index');
}]);*/

Route::group( ['prefix' => 'admin',  'middleware' => ['auth','admin'] ], function()
{
    Route:: view('/home',[AdminController::class,'index']);
    Route:: get('/profile',[AdminController::class,'profile']);
    Route::get('/allposts',[PostController::class,'datatable']);
    Route::get('/allcategory',[CategoryController::class,'datatable']);
    Route::resource('category', CategoryController::class);
	Route::resource('post', PostController::class);
	Route::resource('event', EventController::class);
	Route::post('/storeEvent',[EventController::class,'storeEvent']);


	
});

Route::get('forgot_password',function(){
	return view('auth.passwords.reset');
} );

Route::view('admin','admin.index');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use App\Models\Category;

class Post extends Model
{
    use HasFactory;
    protected $fillable = ['user_id','category_title', 'post_title','post_content','thumbnail','slug'];
     
    public function cat(){
    	 return $this->hasOne('App\Models\Category','id','cat_id');
    }

	 public function createSlug($title, $id = 0)
	    {
	        // Normalize the title
	        $slug = Str::of($title)->slug('-');


	        // Get any that could possibly be related.
	        // This cuts the queries down by doing it once.
	        $allSlugs = $this->getRelatedSlugs($slug, $id);

	        // If we haven't used it before then we are all good.
	        if (! $allSlugs->contains('slug', $slug)){
	            return $slug;
	        }

	        // Just append numbers like a savage until we find not used.
	        for ($i = 1; $i <= 10; $i++) {
	            $newSlug = $slug.'-'.$i;
	            if (! $allSlugs->contains('slug', $newSlug)) {
	                return $newSlug;
	            }
	        }

	        throw new \Exception('Can not create a unique slug');
	    }

	    protected function getRelatedSlugs($slug, $id = 0)
	    {
	        return Post::select('slug')->where('slug', 'like', $slug.'%')
	            ->where('id', '<>', $id)
	            ->get();
	    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Category;
use View;
use App\Models\Post;
use Auth;
use Storage;
use DataTables;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    { 
        $query = Category::query();
        $allcategories= $query->with('children')->get();
       

        return view('adminarea.post.index',['allcategories'=>$allcategories]);

    }

    public function datatable(Request $request){

        $query = Post::with('cat')->select('*');
        return Datatables::of($query)
                ->addColumn('action', function ($post) {
                    return '<button type="button" class="btn btn-sm btn-primary editpost" onClick="editPost('.$post->id.')" >Edit</button> 

                          <button type="button" class="btn btn-sm btn-danger mr-1 deletepost"   
                            data-toggle="modal" data-target="#deletePostModal" onClick="deletepost('.$post->id.')" data-id="'.$post->id.'" data-title="'.$post->post_title.'">Delete</button>
                    ';
                })->editColumn('created_at',function($post){
                    return date('F d, Y', strtotime($post->created_at));
                })
                ->make(true);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('adminarea.post.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([

            'post_title' =>'required|string|min:3|max:255',
            'cat_id'=> 'required',
            'post_content' => 'required|string',
            'thumbnail' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048'
             
        ]);

        $post = new Post;
        $post->user_id = Auth::user()->id;
        $post->post_title = $request->post_title;
        $post->cat_id = $request->cat_id;
        $post->post_content = $request->post_content;
        $post->thumbnail = $request->thumbnail->store('images','public');
        $post->slug = $post->createSlug($request->post_title);
        //dd($post);
        $post->save();
        return response()->json(array('success' => true,'msg'=>'success'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $postData=Post::find($id);
        $html=view('admin.post.show')->with(['postData'=>$postData])->render();
        return response()->json(array('success' => true, 'html'=>$html));
        //return View::make('admin.post.show', array('postData' => $postData));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $allCategories= Category::with('children')->get();
        $data=Post::join('categories','posts.cat_id','=','categories.id')->where('posts.id','=',$id)->select('posts.*','categories.title')->first();
        //dd($data);

        $returnHTML = view('adminarea.post.edit')->with(['allCategories'=>$allCategories,'data'=>$data])->render();
        return response()->json(array('success' => true, 'html'=>$returnHTML));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {   

        $post = Post::find($id);
        //code for remove old file
        if($post->thumbnail != ''  && $request->thumbnail != null){
            $path = storage_path().'/app/public/';
            $file_old = $path.$post->thumbnail;
            if(file_exists($file_old)){
                unlink($file_old);
            }
            $post->thumbnail = $request->thumbnail->store('images','public');
        }

        $post->post_title = $request->post_title;
        $post->post_content = $request->post_content;
        $post->cat_id = $request->cat_id;
        $post->save();
        return redirect()->back()->withSuccess('You have successfully updated Post!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {    
        $post =Post::find($id);
        if($post->thumbnail){
            $file_old = storage_path('app/public/'.$post->thumbnail);
            if(file_exists($file_old)){
                unlink($file_old);
            }
        }
        $post->delete();

        return redirect()->route('post.index')->withSuccess('You have successfully deleted a Post!');        
    }
}

resources/views/adminarea/post/create.blade.php
@extends('layouts.adminarea')
@push('css')
<link rel="stylesheet" href="{{asset('plugins/summernote/summernote-bs4.css')}}">
<style type="text/css">
  .invalid-feedback{
    display: block;
  }
  .alert-danger{
    display:none;
  }
  .alert-success{
    display:none;
  }

</style>
@endpush
@section('content')


  <!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="alert alert-success alert-dismissible col-sm-6">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  <h5><i class="icon fas fa-check"></i> Success!</h5>
                  Your post is added successfully.
                </div>
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Text Editors</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Text Editors</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">

        <div class="col-md-12">
          <div class="card card-outline card-info">
            <div class="card-header">
              <h3 class="card-title">
                Write Your Post Here...
                <small>Simple and fast</small>
              </h3>
              <!-- tools box -->
              <div class="card-tools">
                <button type="button" class="btn btn-tool btn-sm" data-card-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                  <i class="fas fa-minus"></i></button>
                <button type="button" class="btn btn-tool btn-sm" data-card-widget="remove" data-toggle="tooltip"
                        title="Remove">
                  <i class="fas fa-times"></i></button>
              </div>
              <!-- /. tools -->
            </div>
            <!-- /.card-header -->
            <div class="card-body pad">
                <form id="postForm" enctype="multipart/form-data">
                    <div>
                       
                        @csrf
                        
                        <div class="form-group">
                          <label for="post_title">Title</label>
                          <input type="text" name="post_title" class="form-control" id="postTitle">
                          
                          <div class="alert alert-danger" id="post_title"></div>
                        


                        </div>
                        <div class="form-group">
                          <label for="category_title">Category</label>
                          <select  name="cat_id" class="form-control" id="postCategory">
                            <option value="">Choose One...</option>
                            @foreach (allCategory() as $category)
                                      <option value="{{ $category->id }}">{{ $category->title }}</option>
                            @endforeach
                          </select>
                          
                          <div class="alert alert-danger" id="category_title"></div>
                        
                        </div>
                        <div class="form-group">
                          <label for="image">Upload Image</label>
                          <div>
                            <img class="modal-content-img normal" width="50%" height="200" id="postImg" style="display:none"><br/>
                          </div>
                          <div class="custom-file">
                            <label for="thumbnail" class="custom-file-label">Choose File</label>
                            <input type="file" name="thumbnail" class="custom-file-input" id="image">
                            
                            <small class="form-text text-muted">Max Size 3Mb</small>
                            <div class="alert alert-danger" id="thumbnail"></div>

                          </div>
                           <div class="mb-3">
                            <textarea class="textarea" id="postContent" name="post_content" placeholder="Place some text here"
                                      style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
                          </div>
                           
                        </div>
                    </div>
                    <div >
                      <!-- Added id for JS -->
                      <button type="button" class="btn btn-info" id="addPostBtn">Add Post</button>
                    </div>
              </form>
                
            </div>
          </div>
        </div>
        <!-- /.col-->
      </div>
      <!-- ./row -->
    </section>
    <!-- /.content -->
  </div>
  

@endsection  

<!-- jQuery -->

<!-- Summernote -->
@push('js')
<script src="{{asset('plugins/summernote/summernote-bs4.min.js')}}"></script>
<script>
  $(function () {
    // Summernote
    $('.textarea').summernote()
  })
  $(document).ready(function(){
     $("#image").change(function(){
                $("#postImg").css("display", "block")
                readURL(this,'postImg');
           });

  function readURL(input,id) {
                if (input.files && input.files[0]) {
                  var reader = new FileReader();
                
                reader.onload = function (e) {
                    $('#'+id).attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        } // function to show image preview  

  function checkKey(errors, key ){
             if (errors.hasOwnProperty(key)) {
                 console.log(errors[key]);
                $("#"+key).show().text(errors[key][0]);
              }else{
                 $("#"+key).hide();
              }
          }//end of checkKey function        

   $('#addPostBtn').on('click',function(event){
      
            var myForm = new FormData($("#postForm")[0]);
            console.log(myForm);
            var myurl=  "{{url('admin/post/')}}";
            $.ajax({
              type:'POST',
              url:myurl,
              data:myForm,
              dataType:'JSON',
              enctype:"multipart/form-data",
              contentType: false,
              cache: false,
              processData: false,        
              })
            .done(function(data) {
                if(data.msg=='success'){
                  $('.alert-success').css('display','block');
                }
                $("#postForm")[0].reset();
                $("#postImg").css("display", "none");
                $("#postContent").summernote("reset");        
             })
            .fail(function(xhr,status,error){
                var keys= ['post_title','category_title','thumbnail'];
                var errorMessage = xhr.status + ': ' + xhr.statusText;
                var json = $.parseJSON(xhr.responseText);
                var errors = json.errors;
                var i;
                for (i = 0; i < keys.length; i++) {
                   checkKey(errors, keys[i]);
                }
               

             });

          });  //end of addpost 

  });
</script>
@endpush

resources/views/adminarea/post/edit.blade.php
<link rel="stylesheet" href="{{asset('plugins/summernote/summernote-bs4.css')}}">
<style type="text/css">
  .invalid-feedback{
    display: block;
  }
  .alert-danger{
    display:none;
  }
  .alert-success{
    display:none;
  }

</style>

    <!-- Content Header (Page header) -->
    
    <section class="content-header">
      <div class="container-fluid">
       @if (Session::has('success'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <h4 class="alert-heading">Success!</h4>
            <p>{{ Session::get('success') }}</p>

            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        @endif

        @if (Session::has('errors'))
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <h4 class="alert-heading">Error!</h4>
                <p>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </p>

                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Update Post</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Text Editors</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">

        <div class="col-md-12">
          <div class="card card-outline card-info">
            <div class="card-header">
              <h3 class="card-title">
               
                <small>Simple and fast</small>
              </h3>
              <!-- tools box -->
              <div class="card-tools">
                <button type="button" class="btn btn-tool btn-sm" data-card-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                  <i class="fas fa-minus"></i></button>
                <button type="button" class="btn btn-tool btn-sm" data-card-widget="remove" data-toggle="tooltip"
                        title="Remove">
                  <i class="fas fa-times"></i></button>
              </div>
              <!-- /. tools -->
            </div>
            <!-- /.card-header -->
            <div class="card-body pad">

                <form id="postForm" action="{{ route('post.update',$data->id)}}" enctype="multipart/form-data" method="POST" >
                    <div>
                        @csrf
                        @method('PATCH')
                        <div class="form-group">
                          <label for="post_title">Title</label>
                          <input type="text" name="post_title" class="form-control" id="postTitle" value="{{ $data->post_title}}">
                          
                          <div class="alert alert-danger" id="post_title"></div>
                        


                        </div>
                        <div class="form-group">
                          <label for="category_title">Category</label>
                          <select  name="cat_id" class="form-control" id="postCategory">
                            <option value=" {{ $data->cat_id }}">{{ $data->title}}</option>
                            @foreach (allCategory() as $category)
                                      <option value="{{ $category->id }}">{{ $category->title }}</option>
                            @endforeach
                          </select>
                          
                          <div class="alert alert-danger" id="category_title"></div>
                        
                        </div>
                        <div class="form-group">
                          <label for="image">Upload Image</label>
                          <div>
                            <img src="{{asset('storage')}}/{{$data->thumbnail}}" class="modal-content-img normal" width="50%" height="200" id="updatePostImg"><br/>
                          </div>
                          <div class="custom-file">
                            <label for="thumbnail" class="custom-file-label">Choose File</label>
                            <input type="file" name="thumbnail" class="custom-file-input" id="updateimage">
                            
                            <small class="form-text text-muted">Max Size 3Mb</small>
                            <div class="alert alert-danger" id="thumbnail"></div>

                          </div>
                           <div class="mb-3">
                            <textarea class="textarea" id="postContent" name="post_content" placeholder="Place some text here"
                                      style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"> {{$data->post_content }}</textarea>
                          </div>
                           
                        </div>
                    </div>
                    <div >
                      <!-- Added id for JS -->

                      <button type="submit" class="btn btn-info" id="updatePost">update Post</button>
                    </div>
              </form>
                
            </div>
          </div>
        </div>
        <!-- /.col-->
      </div>
      <!-- ./row -->
    </section>
    <!-- /.content -->
    <script src="{{asset('plugins/summernote/summernote-bs4.min.js')}}"></script>
 <script>
   $(function () {
    // Summernote
    $('.textarea').summernote()
  })

 </script>

resources/views/adminarea/post/index.blade.php
@extends('layouts.adminarea')
@push('css')
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- DataTables -->
  <link rel="stylesheet" href="{{asset('plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
  <link rel="stylesheet" href="{{asset('plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
  @endpush

  <!-- Content Wrapper. Contains page content -->
  @section('content')
  <div class="content-wrapper" id="postEditor">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>DataTables</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">DataTables</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">DataTable with default features</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="post_table" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>Sr. No.</th>
                    <th>Title</th>
                    <th>Category</th>
                    <th>Date</th>
                    <th>Action</th>
                  </tr>
                  </thead>
                 
                 
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
<!-- DELETE POST MODEL-->
<div class="modal" tabindex="-1" role="dialog" id="deletePostModal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Category</h5>

          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      

        <form action="" method="POST">
           @csrf
           @method('DELETE')

          <div class="modal-body">
            <div class="form-group">
              <p>Are you sure! Do you really want to delete this Post?</p>
            </div>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-sm btn-danger">Delete</button>
          </div>
        </form>
      </div>
   </div>    
</div> 

  @endsection
  <!-- /.content-wrapper -->
<!-- ./wrapper -->

<!-- jQuery -->

<!-- DataTables -->
@push('js')
<script src="{{asset('plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{asset('plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{asset('plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('dist/js/adminlte.min.js')}}"></script>
<!-- page script -->
<script>
  $(function () {
    $('#post_table').DataTable({
       processing: true,
        serverSide: true,
        ajax: '{{ url("admin/allposts") }}',
        columns: [
            {data: 'id', name: 'id'},
            {data: 'post_title', name: 'post_title'},
            {data: 'cat.title', name: 'cat.title'},
            {data: 'created_at', name: 'created_at'},
            {data: 'action', name: 'action', orderable: false, searchable: false}
        ]
    });
  });
  function editPost(id){
           
            var editurl= "{{url('admin/post')}}/"+id+"/edit";
            //var updateurl="{{url('admin/post')}}/"+id;
            var myurl='{{url("admin/post")}}';
           
            $.ajax({
                         type:'GET',
                         url:editurl, //Make sure your URL is correct
                         data:'_token = <?php echo csrf_token() ?>'
                         
                     })
            .done(function(data){
              $('#postEditor').html(data.html);
              console.log(data.successs);
              //$('#postEditor form').attr('action', updateurl);
              $("#updateimage").change(function(){
                      readURL(this,'updatePostImg');
                });
              
              
             })
            .fail(function(xhr,status,error){
              
              var errorMessage = xhr.status + ': ' + xhr.statusText;
              console.log(errorMessage);
            });
       
  }
 
  function deletepost(id){
            var url = "{{ url('admin/post') }}/" + id;
            $('#deletePostModal form').attr('action', url);
  }

  

  function readURL(input,id) {
                if (input.files && input.files[0]) {
                  var reader = new FileReader();
                
                reader.onload = function (e) {
                    $('#'+id).attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        } // function to show image preview  

  function checkKey(errors, key ){
             if (errors.hasOwnProperty(key)) {
                 console.log(errors[key]);
                $("#"+key).show().text(errors[key][0]);
              }else{
                 $("#"+key).hide();
              }
          }//end of checkKey function   

</script>
@endpush

resources/views/adminarea/post/show.blade.php
 <link rel="stylesheet" type="text/css" href="{{asset('../css/singlepost.css')}}">
   <div class="col-md-10 blogShort" id="posts">
                     <h1>{{$postData->post_title}}</h1>
                     <img src="{{ asset('storage/'.$postData->thumbnail)}}" alt="post img" class="pull-left img-responsive postImg img-thumbnail margin10">
                     <article>
                     	{!!$postData->post_content!!}
                     	
                         
                     
                     
                     </article>
                
     </div>

	